### ISSUE TITLE
Can't import the module 'pygame', where and what is it? It's not in my projectfolder.

### ISSUE THREAD

**Issue by jeanpauledoh** [SirMoM/game#7]

**Comment by SirMoM** [comment]
https://www.pygame.org/wiki/GettingStarted

nachdem Python installiert wurde den Befehl in die Command Zeile eintippen:
python3 -m pip install -U pygame --user
oder python pip install pygame

**Comment by SirMoM** [comment]
python -m pip install -U pygame
